import { RestError } from "@azure/core-http";
import * as Models from "./generated/src/models";
export * from "./BlobServiceClient";
export * from "./ContainerClient";
export * from "./BlobClient";
export * from "./AppendBlobClient";
export * from "./BlockBlobClient";
export * from "./PageBlobClient";
export * from "./BatchRequest";
export * from "./BatchResponse";
export * from "./BrowserPolicyFactory";
export * from "./credentials/AnonymousCredential";
export * from "./credentials/Credential";
export { IPRange } from "./IPRange";
export { Range } from "./Range";
export * from "./LeaseClient";
export { BlockBlobTier, PremiumPageBlobTier } from "./models";
export * from "./Pipeline";
export * from "./policies/AnonymousCredentialPolicy";
export * from "./policies/CredentialPolicy";
export * from "./RetryPolicyFactory";
export * from "./LoggingPolicyFactory";
export * from "./TelemetryPolicyFactory";
export * from "./UniqueRequestIDPolicyFactory";
export { Models, RestError };
//# sourceMappingURL=index.browser.d.ts.map