import { StorageClientContext } from "./generated/src/storageClientContext";
import { Pipeline } from "./Pipeline";
import { AnonymousCredential } from "./credentials/AnonymousCredential";
import { SharedKeyCredential } from "./credentials/SharedKeyCredential";
import { TokenCredential } from "@azure/core-http";
/**
 * A StorageClient represents a based URL class for BlobServiceClient, ContainerClient and etc.
 *
 * @export
 * @class StorageClient
 */
export declare abstract class StorageClient {
    /**
     * Encoded URL string value.
     *
     * @type {string}
     * @memberof StorageClient
     */
    readonly url: string;
    /**
     * Request policy pipeline.
     *
     * @internal
     * @ignore
     * @type {Pipeline}
     * @memberof StorageClient
     */
    protected readonly pipeline: Pipeline;
    /**
     * Credential used for authentication and authorization.
     *
     * @type {string}
     * @memberof StorageClient
     */
    readonly credential: SharedKeyCredential | AnonymousCredential | TokenCredential;
    /**
     * StorageClient is a reference to protocol layer operations entry, which is
     * generated by AutoRest generator.
     *
     * @protected
     * @type {StorageClientContext}
     * @memberof StorageClient
     */
    protected readonly storageClientContext: StorageClientContext;
    /**
     * @protected
     * @type {boolean}
     * @memberof StorageClient
     */
    protected readonly isHttps: boolean;
    /**
     * Creates an instance of StorageClient.
     * @param {string} url url to resource
     * @param {Pipeline} pipeline request policy pipeline.
     * @memberof StorageClient
     */
    protected constructor(url: string, pipeline: Pipeline);
}
//# sourceMappingURL=StorageClient.d.ts.map